# azure-pipelines-automated-dependency.yml

trigger: none

schedules:
- cron: "0 19 * * *"
  displayName: Every day at midnight
  branches:
    include:
    - main
  always: true

pool:
  name: default

stages:
- stage: AutomatedDependencyUpdateServer
  jobs:
  - job: AutomatedDependencyUpdateServerJob
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'
        addToPath: true
      displayName: 'Set Python version'

    - script: |
         cd server
         ncu -u 
      displayName: 'Check and Update Dependencies (Server)'

    - script: |
        git config --global user.email "khwajafarazahmed@yahoo.com"
        git config --global user.name "Faraz Khawaja"
        git add server/package.json
        git commit -m "Update dependencies (Server)"
        git push -u origin HEAD:main
      displayName: 'Pushing to GitHub (Server)'

- stage: AutomatedDependencyUpdateClient
  dependsOn: AutomatedDependencyUpdateServer
  jobs:
  - job: AutomatedDependencyUpdateClientJob
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'
        addToPath: true
      displayName: 'Set Python version'

    - script: |
         cd client
         ncu -u 
      displayName: 'Check and Update Dependencies (Client)'

    - script: |
        git config --global user.email "khwajafarazahmed@yahoo.com"
        git config --global user.name "Faraz Khawaja"
        git pull origin main
        git add client/package.json
        git commit -m "Update dependencies (Client)"
        git push -u origin HEAD:main
      displayName: 'Pushing to GitHub (Client)'


