trigger: none

schedules:
- cron: "40 9 * * *"
  displayName: Daily 2:40 PM GMT+5
  branches:
    include:
    - main
  always: true

pool:
  name: default

stages:
- stage: AutomatedDependencyUpdate
  jobs:
  - job: AutomatedDependencyUpdateJob
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'
        addToPath: true
      displayName: 'Set Python version'
  
    - script: |
         cd server
         ncu -u 
         cd ../client
         ncu -u
      displayName: 'Check and Update Dependencies (Server and Client)'

    - script: |
        git config --global user.email "khwajafarazahmed@yahoo.com"
        git config --global user.name "Faraz Khawaja"
        git add server/package.json client/package.json
        git commit -m "Update dependencies (Server and Client)"
        git push -u origin HEAD:main
      displayName: 'Pushing to GitHub (Server and Client)'
