
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more.
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main


pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: BuildAndAnalyze
  jobs:
  - job: BuildAndAnalyzeJob
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '14.x'
      displayName: 'Install Node.js'

    - script: |
        cd server
        npm install
        npm install -g eslint -y
        eslint --init
        eslint . > eslint-report.txt 2>&
      displayName: 'npm install'
    # - script: |
    #     npm run build
    #   displayName: 'Build Code'

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'
        addToPath: true
      displayName: 'Set Python version'

    # - script: |
    #     cd server
    #     eslint . > eslint-report.txt 2>&1 --verbose
    #   displayName: 'ESLint Code Analysis'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish ESLint Report'
      inputs:
        PathtoPublish: '$(System.DefaultWorkingDirectory)'
        ArtifactName: 'eslint-report'

    - task: CopyFiles@2
      displayName: 'Copy Backend Code'
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)/server'
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)/backend'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Backend Artifact'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/backend'
        ArtifactName: 'backend'

