# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more.
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  name: default

stages:
- stage: BuildAndAnalyze
  jobs:
  - job: BuildAndAnalyzeJob
    steps:
    - checkout: self
      fetchDepth: 1      
    - task: SonarCloudPrepare@1
      displayName: Prepare analysis on SonarCloud
      inputs:
        SonarCloud: c49a14d2-f70e-46f9-8475-d950d88597a8
        organization: k200121faraz
        scannerMode: CLI
        configMode: manual
        cliProjectKey: k200121Faraz_Shop-Bot.git
        cliProjectName: Shop-Bot.git  
    - task: NodeTool@0
      inputs:
        versionSpec: '14.x'
      displayName: 'Install Node.js'
         
    - script: |
        cd server
        npm install
      displayName: 'npm install'

    - script: |
        cd server
        npm run lint > eslint-report.txt
      displayName: 'npm run lint'

    # Add more steps as needed
    
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'
        addToPath: true
      displayName: 'Set Python version'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish ESLint Report'
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)/server/eslint-report.txt'
        ArtifactName: 'eslint-report'

    - task: SonarCloudAnalyze@1
      displayName: Run Code Analysis
    - task: SonarCloudPublish@1
      displayName: Publish Quality Gate Result 
    - task: CopyFiles@2
      displayName: 'Copy Backend Code'
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)/server'
        Contents: |
            **/*
            !node_modules/**/*
        TargetFolder: '$(Build.ArtifactStagingDirectory)/backend'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Backend Artifact'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/backend'
        ArtifactName: 'backend'
