# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more.
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main
pool:
  name: default

stages:
# - stage: BuildAndAnalyze
#   jobs:
#   - job: BuildAndAnalyzeJob
#     steps:
#     - task: NodeTool@0
#       inputs:
#         versionSpec: '12.x'
#       displayName: 'Install Node.js'

#     - script: |
#         npm install
#         npm run build
#       displayName: 'npm install+build'

#     - task: UsePythonVersion@0
#       inputs:
#         versionSpec: '3.x'
#         addToPath: true
#       displayName: 'Set Python version'

#     - script: |
#         npm install -g eslint
#         eslint --init
#         eslint . > eslint-report.txt 2>&1
#       displayName: 'ESLint Code Analysis'

#     - task: PublishBuildArtifacts@1
#       displayName: 'Publish ESLint Report'
#       inputs:
#         PathtoPublish: '$(System.DefaultWorkingDirectory)'
#         ArtifactName: 'eslint-report'

#     - task: CopyFiles@2
#       displayName: 'Copy Backend Code'
#       inputs:
#         SourceFolder: '$(Build.SourcesDirectory)/server'
#         Contents: '**'
#         TargetFolder: '$(Build.ArtifactStagingDirectory)/backend'

#     - task: PublishBuildArtifacts@1
#       displayName: 'Publish Backend Artifact'
#       inputs:
#         PathtoPublish: '$(Build.ArtifactStagingDirectory)/backend'
#         ArtifactName: 'backend'

- stage: AutomatedDependencyUpdate
  jobs:
  - job: AutomatedDependencyUpdateJob
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'
        addToPath: true
      displayName: 'Set Python version'

    - script: |
         cd server
         ncu -u 
      displayName: 'Check and Update Dependencies'
    - script: |
        git pull origin main
        git add server/package.json
        git commit -m "Update dependencies"
        git push -u origin main
      displayName: 'Pushing to github'

