# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more.
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main
pool:
  name: default

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- task: CopyFiles@2
  displayName: 'Copy Backend Code'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/server'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/backend'
- task: PublishBuildArtifacts@1
  displayName: 'Publish Backend Artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/backend'
    ArtifactName: 'backend'