version: '3'
services:
  mongodb:
    image: mongo
    container_name: my-mongodb-container
    ports:
      - '27017:27017'
    volumes:
      - mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: examplepassword

  nodejs-app:
    build:
      context: ./server  # Replace with the path to your Node.js app code
    image: farazkhawaja/backend
    depends_on:
      - mongodb
    environment:
      MONGO_URL: mongodb://root:examplepassword@mongodb:27017/mydb?authSource=admin  # Update as needed
    ports:
      - '5000:5000'
  frontend:
    build:
      context: ./client  # Path to the React app directory
    image: farazkhawaja/frontend
    ports:
      - '3000:3000'
volumes:
  mongodb-data:

