apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-client.fullname" . }}
  labels:
    {{- include "helm-client.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      protocol: TCP
      name: {{ .Values.container.name}}
  selector:
    app: {{ .Values.container.name}}
