apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-frontend
spec:
  replicas: 5
  template:
    spec:
      containers:
        - name: my-frontend
          resources:
            limits:
              cpu: "2"
